import { Inter } from '@next/font/google'
import { Header } from '@/components'
import '../styles/globals.css'

export const metadata = {
  title: 'LinkedIn Dark Mode (Gleyson)',
  description: 'Generated by create next app'
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <head />

      <body>
        <div id="container">
          <Header />
          <div className="container-children">{children}</div>
        </div>
      </body>
    </html>
  )
}
